language: go
sudo: false
matrix:
  include:
    - go: 1.11.x
      env: LATEST=true

before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox

install:
  - # skip

script:
  - go get -t -v ./...
  - go test -v -race ./...
  - if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -output="matrix-todo.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi

deploy:
  # provider: releases
  provider: script
  skip_cleanup: true
  script: sleep 1
  # api_key:
  #   secure:
  # file:
  # - matrix-todo.windows.amd64.exe
  # - matrix-todo.darwin.amd64
  # - matrix-todo.linux.amd64
  # on:
  #   repo: midse/matrix-todo
  #   tags: true
  #   condition: $LATEST = true